#pragma once
#include<iostream>
using namespace std;

class Matrix
{
private:
	int a[3][3];
public:
	Matrix();
	Matrix(Matrix &);
	void setValue();
	void print();
	Matrix transpose();						// Function to find transpose of a matrix...
	Matrix& operator=(const Matrix&);		// (=) assingment operator overloading...
	Matrix operator+(const Matrix&)const;	// +  operator overloading...
	Matrix operator-(const Matrix&)const;	// -  operator overloading...
	Matrix operator*(const Matrix&)const;	// *  operator overloading...
	bool operator==(const Matrix&)const;	// == operator overloading...
	bool operator!=(const Matrix&)const;	// != operator overloading...
	bool operator!();						// !  operator overloading...
};

